### ISSUE TITLE
What is the function of 'app' folder?

### ISSUE THREAD

**Issue by naivenaive** [DCBIA-OrthoLab/fly-by-cnn#12]
Flyby CNN is a fantastic work on segmentation mesh surface. The source code composed of two parts: 'py' written in python and 'app' written in C++. I have read part of the source code. I found that the code written in python had implemented the algorithm introduced in the article entitled 'FlyBy CNN: A 3D surface segmentation framework'. But I cannot figure out the meaning of the code in 'app' folder.  The README file of 'app' folder is titled 'Building VTK-9.0'.  Does it mean the app folder is designed to build a new VTK package for this project?  Is it necessary for this project or just another implementation method written in C++? Thanks.

**Comment by juanprietob** [comment]
Thank you for the comment. The app folder was an initial implementation of the algorithm which is written in c++. 
After some deliberation, we decided to migrate the code to python which has straightforward compatibility with TensorFlow and will make it much easier to use and integrate into other projects.
